name = "pulseechoeco"
compatibility_date = "2025-11-29"
compatibility_flags = ["nodejs_compat"]

workers_dev = false
preview_urls = true

[assets]
binding = "ASSETS"
directory = "./out"

[vars]
ENVIRONMENT = "production"
